Sign up form
W2WBack2RD/goodforest pull request #12
Opened 2022-01-31 22:19 UTC by yoni2502

2022-02-04 13:02 UTC, omers4 requested changes

2022-02-04 13:02 UTC, omers4 commented on client/api/user.js
> +
remove

2022-02-04 13:02 UTC, omers4 commented on client/components/environment/Main/Main.js
> +// import Navigation from '_organisms/Navigation';
Remove **all** unecessary comments.

2022-02-04 13:02 UTC, omers4 commented on client/components/environment/Main/Main.js
> -          <Route path="/home" component={HomePage} />
Why erased?

2022-02-04 13:02 UTC, omers4 commented on client/components/organisms/Register/Register.js
> +            <option value="">בחירה</option>
What about other years?

2022-02-04 13:02 UTC, omers4 commented on client/components/pages/HomePage/HomePage.js
> +  const handleAddTodo = () => {
?

2022-02-04 13:02 UTC, omers4 commented on client/styles/navigation.scss
> +//     }
remove all comments

2022-02-04 13:02 UTC, omers4 commented on package.json
> +    "radium": "^0.26.1",
what is this?

2022-02-04 14:32 UTC, yoni2502 commented on client/api/user.js
> +
done

2022-02-14 17:29 UTC, omers4 commented on client/components/organisms/Register/Register.js
> +   const handleSubmit = (event) => {
Make sure this has the same logic as register functio above (dispatching the redux)

2022-02-14 17:29 UTC, omers4 commented on client/components/organisms/Register/Register.js
> +  // const checkPassword = (newUsername, newPassword) => {
Please remove the unecessary code

2022-02-14 17:30 UTC, omers4 commented on client/components/organisms/Register/Register.js
>          password,
Now we have a lot more fields - so add them here in order to send them to the redux.

2022-02-18 07:03 UTC, omers4 commented on client/styles/register.scss
> +  width: 295px;
Change width to 100% instead.
Not all phones have the same width.

2022-02-18 07:10 UTC, omers4 commented on client/styles/register.scss
> +.button {
This will override the styles of all buttons in the system. so just change the styles of the buttons that are inside the page.

2022-04-13 20:21 UTC, closed without merging